; modified https://github.com/gh0stzk/dotfiles

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = colors.ini
include-file = modules.ini

[bar/bar]

monitor-strict = false

override-redirect = false

bottom = false
fixed-center = true
width = 90%
height = 40

offset-x = 5%
offset-y = 1%

background = ${color.bg}
foreground = ${color.fg}

radius = 16

line-size = 2
line-color = ${color.blue}

border-size = 0px
border-color = #44475a

padding = 1

module-margin-left = 0
module-margin-right = 0

; Text
font-0 = "AdwaitaMono Nerd Font:style=Regular:size=11;4"
font-1 = "AdwaitaMono Nerd Font:style=Regular:size=12;3"
; for large icons
font-2 = "AdwaitaMono Nerd Font:style=Regular:size=15;4"
; for scaling small icons
font-3 = "AdwaitaMono Nerd Font:style=Regular:size=14;4"
; for arch icon
font-4 = "AdwaitaMono Nerd Font:style=Regular:size=18;5"


modules-left = sep1 arch sep2 pipe sep2 cpu_bar sep2 memory_bar sep2 filesystem sep1 
modules-center = bspwm
modules-right =  time sep2 pipe sep2 wifi ethernet sep1 pulseaudio sep1 battery sep2 sep2 powermenu sep2


spacing = 0
separator = ""
dim-value = 1

;;locale = es_MX.UTF-8

cursor-click = pointer 
cursor-scroll =

[bar/tray]

monitor-strict = false
width = 100
height = 35
offset-x = 90% 
offset-y = 50   

override-redirect = true  
fixed-center = true
background = ${color.bg}
;foreground = ${colors.foreground}
radius = 15
line-size = 0
line-color = #f00

border-size = 0px
border-color = #44475a

padding-left = 0
padding-right = 1
module-margin-left = 0
module-margin-right = 0

modules-right = sep
tray-position = right
tray-detached = true
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 1
tray-maxsize = 25
tray-scale = 1
tray-background = transparent

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
